name: Release Workflow

on:
  push:
    branches: [development, release-*]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: taa-epam/ai-dial-ci/.github/workflows/node_release.yml@f35b17df28f9a32ea75e80c8449e6dc3a7f75aa1
    secrets: inherit
    strategy:
      fail-fast: false # Let all builds finish
      matrix:
        include:
          - platform: "linux/amd64"
            runner: "ubuntu-24.04"
            arch: "amd64"
          - platform: "linux/arm64"
            runner: "ubuntu-24.04-arm"
            arch: "arm64"
            ort-bypassed: true
            trivy-enabled: false
    with:
      runs-on: '["${{ matrix.runner }}"]'
      node-version: 22
      platforms: "${{ matrix.platform }}"
      maximize-build-space: true
      dockerhub-image-name: ltaa/ai-dial-chat
      ort-bypassed: "${{ matrix.ort-bypassed }}"
      trivy-enabled: "${{ matrix.trivy-enabled }}"